global:
  scrape_interval: 10s
  external_labels:
    server: itc

scrape_configs:
  - job_name: itc
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['itc:8081']

#  - job_name : postgres
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9102']#  - job_name: node
#    static_configs:
#      - targets: ['localhost:9100']
#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:8060']
